server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psmcdb
    username: psmc
    password: psmc
  security:
    headers:
      content-security-policy: "script-src 'self' http://ajax.googleapis.com"
  servlet:
    multipart:
      max-file-size: 10MB
    mvc:
      static-path-pattern: /static/**
mybatis:
  mapper-locations: mappers/*.xml




